//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantOtomasyonu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestaurantDatabaseEntities1 : DbContext
    {
        public RestaurantDatabaseEntities1()
            : base("name=RestaurantDatabaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLBasket> TBLBasket { get; set; }
        public virtual DbSet<TBLCategories> TBLCategories { get; set; }
        public virtual DbSet<TBLOrderDetails> TBLOrderDetails { get; set; }
        public virtual DbSet<TBLOrders> TBLOrders { get; set; }
        public virtual DbSet<TBLPersonals> TBLPersonals { get; set; }
        public virtual DbSet<TBLProducts> TBLProducts { get; set; }
        public virtual DbSet<TBLRezervation> TBLRezervation { get; set; }
        public virtual DbSet<TBLTables> TBLTables { get; set; }
    }
}
