//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLBasket
    {
        public int id { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Piece { get; set; }
        public string TablesNo { get; set; }
    }
}
