//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPersonals
    {
        public int id { get; set; }
        public string Email { get; set; }
        public string Passwords { get; set; }
        public string Roles { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
