//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLRezervation
    {
        public int id { get; set; }
        public string NameSurName { get; set; }
        public string Phone { get; set; }
        public Nullable<int> PersonNumber { get; set; }
        public Nullable<System.DateTime> RezervationDate { get; set; }
        public Nullable<System.TimeSpan> RezervationTime { get; set; }
        public string TableNo { get; set; }
    }
}
